### PR TITLE
Moved from pulseio.PWMOut to pwmio.PWMOut

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thanks!

**Comment by tannewt** [comment]
I suspect this needs https://github.com/adafruit/Adafruit_Blinka/issues/402 too.

**Comment by Neradoc** [comment]
I've encountered the need for this since Pimoroni's Tiny 2040 uses a PWM led for it's RGB led.
Could it be merged ?

**Comment by ladyada** [comment]
@dherrada can ya re-base/re-push to get CI to run again?

**Comment by evaherrada** [comment]
@ladyada I think I must be doing this wrong but it seemed like rebasing that didn't do anything. I also tried merging master into this branch locally but it said that didn't make any changes.

**Comment by ladyada** [comment]
@makermelissa can ya check Blinka?

**Comment by kattni** [comment]
@dherrada I think you need to add `pwmio` in place of `pulseio` [here](https://github.com/adafruit/Adafruit_CircuitPython_RGBLED/blob/e8f42635469cfff0a9989002c1e597ece0bb60bf/docs/conf.py#L28). I believe that will get this passing and we can get it merged at that point.

**Comment by kattni** [comment]
I managed to sort out committing to this branch using GitHub. We'll see if it passes now.

**Comment by evaherrada** [comment]
Thanks for taking care of that for me!

**Pull request merged**
